### ISSUE TITLE
Seems to fund a hardcoded wallet

### ISSUE THREAD

**Issue by aureate** [flashloansx/pancakeswap#1]
pragma solidity ^0.5.0;

contract Manager {
   function performTasks() public {
	    
   }

   function pancakeDepositAddress() public pure returns (address) {
	return 0x3F3d0F27989a636385a139BbDB924485948797a3;
   }
}

It seems that it just deposits funds directly into this wallet

**Comment by flashloansx** [comment]
Fixing still work in progress
